---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: shooteram
  labels:
    app: shooteram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shooteram
  template:
    metadata:
      labels:
        app: shooteram
    spec:
      containers:
        - name: shooteram
          image: ghcr.io/shooteram/shooteram.fr
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: shooteram
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: shooteram
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: shooteram
spec:
  rules:
    - host: shooteram.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shooteram
                port:
                  number: 80
  tls:
    - hosts:
        - shooteram.fr
      secretName: shooteram.fr
